### ISSUE TITLE
`NoSuchMethodError: 'net.minecraft.class_7172 net.minecraft.class_315.method_47395()'`

### ISSUE THREAD

**Issue by SettingDust** [Gegy/whats-that-slot#12]
```
net.minecraft.class_148: Ticking screen
	at net.minecraft.class_437.method_25412(class_437.java:494) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1821) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1135) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:475) [quilt-loader-0.18.1-beta.25.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [quilt-loader-0.18.1-beta.25.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.18.1-beta.25.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_7172 net.minecraft.class_315.method_47395()'
	at dev.gegy.whats_that_slot.query.GlobalItemStacks.get(GlobalItemStacks.java:20) ~[whats-that-slot-fabric-1.3.21.19.3.jar.i0:0/:?]
	at dev.gegy.whats_that_slot.query.SlotQueryGenerator$MatchingGlobal.<init>(SlotQueryGenerator.java:115) ~[whats-that-slot-fabric-1.3.21.19.3.jar.i0:0/:?]
	at dev.gegy.whats_that_slot.query.SlotQueryGenerator$MatchingInventory.advance(SlotQueryGenerator.java:94) ~[whats-that-slot-fabric-1.3.21.19.3.jar.i0:0/:?]
	at dev.gegy.whats_that_slot.query.SlotQueryGenerator.advance(SlotQueryGenerator.java:47) ~[whats-that-slot-fabric-1.3.21.19.3.jar.i0:0/:?]
	at dev.gegy.whats_that_slot.query.SlotQueryGenerator.advanceFor(SlotQueryGenerator.java:59) ~[whats-that-slot-fabric-1.3.21.19.3.jar.i0:0/:?]
	at dev.gegy.whats_that_slot.ui.state.RequestingQueryState.tick(RequestingQueryState.java:42) ~[whats-that-slot-fabric-1.3.21.19.3.jar.i0:0/:?]
	at dev.gegy.whats_that_slot.ui.state.SlotQueryController.tick(SlotQueryController.java:27) ~[whats-that-slot-fabric-1.3.21.19.3.jar.i0:0/:?]
	at net.minecraft.class_465.handler$egn000$tickQuery(dev/gegy/whats_that_slot/mixin/AbstractContainerScreenMixin.java [#whats_that_slot:whats_that_slot.mixins.json]:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_37432(class_465.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_37432(class_481.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25393(class_465.java:632) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1572(class_310.java:1821) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:489) ~[client-intermediary.jar:?]
	... 10 more
```

**Comment by Gegy** [comment]
Hi, thanks for the report! Are you potentially using the latest 1.19.3 release on 1.19.2? 🙂 (Looks like I missed updating the dependency requirements, so this is a bit of an unclear issue if that is the case - apologies for that!)

**Comment by SettingDust** [comment]
![图片](https://user-images.githubusercontent.com/19922286/210124047-ff67b869-e061-49c2-8bfb-f6ab11ad416a.png)
It's marks as supporting 1.19.2. XD. I use ferium(a mod manager) and it's downloading the newest version

**Comment by Gegy** [comment]
Woops, good catch! I'll fix that on the existing releases too 🙂
